- hosts: nxos101
  gather_facts: False
  vars:
    filter:
      System:
          "@xmlns": "http://cisco.com/ns/yang/cisco-nx-os-device"
          intf-items:
            phys-items:
              PhysIf-list:
                id: eth1/10
  tasks:
  
  - name: Get the config using the filter
    cidrblock.dev.netconf_get:
      source: running
      filter: "{{ filter }}"
      display: native
    register: config

  - name: Random description
    set_fact:
      new_descr: "{{ 100 | random }}"

  - name: Update
    cidrblock.dev.update_fact:
      config.output.data.System.intf-items.phys-items.PhysIf-list.descr: "{{ new_descr }}"
    register: updated
  
  - name: Set the fact for the revised config
    set_fact:
      revised_config:
        config:
          System: "{{ updated['config']['output']['data']['System'] }}"
  
  - name: Apply the new configuration
    cidrblock.dev.netconf_config:
      content: "{{ revised_config }}"

  - name: Get the config using the filter
    cidrblock.dev.netconf_get:
      source: running
      filter: "{{ filter }}"
      display: native
    register: after

  - name: Show the differences in a dot delimited format
    cidrblock.dev.fact_diff:
      before: "{{ config['output'] }}"
      after: "{{ after['output'] }}"
      dotted: True
  
  - name: Validate the configuration change
    cidrblock.dev.validate:
      vars: "{{ after['output'] }}"
      schema:
        type: object
        description: Confirm the new interface description
        required:
        - data
        properties:
          data:
            type: object
            required:
            - System
            properties:
              System:
                type: object
                requred:
                - intf-items
                properties:
                  intf-items:
                    type: object
                    required:
                    - phys-items
                    properties:
                      phys-items:
                        type: object
                        required:
                        - PhysIf-list
                        properties:
                          PhysIf-list:
                            type: object
                            required:
                            - descr
                            properties:
                              descr:
                                const: "{{ new_descr }}"
  