- hosts: eos101:nxos101
  gather_facts: False
  collections:
  - cidrblock.dev
  vars:
    interface:
      eos: Ethernet2
      nxos: eth1/1
    filter:
      interfaces:
        "@xmlns": "http://openconfig.net/yang/interfaces"
        interface:
          name: "{{ interface[ansible_network_os.split('.')[-1]] }}"
   
  tasks:
  - name: Get the config using the filter
    cidrblock.dev.netconf_get:
      source: running
      filter: "{{ filter }}"
      display: native
    register: config
  
  - name: Random description
    set_fact:
      new_descr: "{{ 100 | random }}"

  - name: Update
    update_fact:
      config.output.data.interfaces.interface.config.description: "{{ new_descr }}"
    register: updated
  
  - name: Set the fact for the revised config
    set_fact:
      revised_config:
        config: 
          interfaces: "{{ updated['config']['output']['data']['interfaces'] }}"
  
  - name: Apply the new configuration
    cidrblock.dev.netconf_config:
      content: "{{ revised_config }}"

  - name: Get the config using the filter
    cidrblock.dev.netconf_get:
      source: running
      filter: "{{ filter }}"
      display: native
    register: after

  - name: Show the differences in a dot delimited format
    cidrblock.dev.fact_diff:
      before: "{{ config['output'] }}"
      after: "{{ after['output'] }}"
      dotted: True
  
  - name: Validate the configuration change
    cidrblock.dev.validate:
      vars: "{{ after['output'] }}"
      schema:
        type: object
        description: Confirm the new interface description
        required:
        - data
        properties:
          data:
            type: object
            required:
            - interfaces
            properties:
              interfaces:
                type: object
                requred:
                - description
                properties:
                  description:
                    const: "{{ new_descr }}"
  